apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/signature: MEQCIDswJLdcnt3HOoN0g3uQFi7zEnOiMt5Cq6g1sViJlngxAiA+L9LJTGdJrBpey10rIzGPVqHE7955VVJPq6OJnpnl7w==
  creationTimestamp: null
  name: goodbye
spec:
  params:
  - name: username
    type: string
  steps:
  - image: ubuntu
    name: goodbye
    resources: {}
    script: |
      #!/bin/bash
      echo "Goodbye $(params.username)!"
