apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  params:
  - name: username
    type: string
  tasks:
    - name: hello
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/geriom/hello-world-tkn
          - name: revision
            value: main
          - name: pathInRepo
            value: hello-world.yaml
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbye
      params:
      - name: username
        value: $(params.username)
