apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  params:
  - name: username
    type: string
  tasks:
    - name: hello
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/geriom/hello-world-tkn
          - name: revision
            value: main
          - name: pathInRepo
            value: hello.yaml
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/geriom/hello-world-tkn
          - name: revision
            value: main
          - name: pathInRepo
            value: goodbye.yaml
      params:
      - name: username
        value: $(params.username)
