apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipelinerun-
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/geriom/hello-world-tkn
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-pipeline.yaml
  params:
  - name: username
    value: "Tekton"
