apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/signature: MEUCIQDDlex7Byf4mHawg7PA0cv/RyxduJK70Hlpl46qgIkp/wIgaOdVQIpe3G7rRxn+ceJ2Y6kpRnXSwhNqwlPotiqTHQs=
  creationTimestamp: null
  name: hello
spec:
  steps:
  - image: alpine
    name: echo
    resources: {}
    script: |
      #!/bin/sh
      echo "Hello World"
