apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/signature: MEUCIGMuXvk5UQZQ+6OSYAvGOhtHIOrJWQH+XhQ551aqI8bJAiEAzxUSzQ3bEgOfbNoHAL+hymNxYrGN+wRR56GAVOlb1QM=
  creationTimestamp: null
  name: hello
spec:
  steps:
  - image: alpine
    name: echo
    resources: {}
    script: |
      #!/bin/sh
      echo "Hello World"
