apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/signature: MEMCH1JBTPHz/WFQLa8PzoHCefer9aQxmxMkBYPuWDbrfOsCIA0kYBjPdia7lmpBFaYz5MvEVg+oGbLwb+hc8SXmNkrv
  creationTimestamp: null
  name: goodbye
spec:
  params:
  - name: username
    type: string
  steps:
  - image: ubuntu
    name: goodbye
    resources: {}
    script: |
      #!/bin/bash
      echo "Goodbye $(params.username)!"
