apiVersion: tekton.dev/v1alpha1
kind: VerificationPolicy
metadata:
  name: cosign-policy
spec:
  resources:
    - pattern: "https://github.com/geriom/hello-world-tkn"
  authorities:
    - name: cosign
      key:
        secretRef:
          name: verification-secrets
          namespace: tekton-pipelines
  mode: enforce
